### ISSUE TITLE
Geliştir: Tasarımların CSS Birleştimesi Ve Kontrolü

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/icon-wizard#68]
Türü: Kodlama
Tanım: Figmadan Electron.js ye yapılan HTML/CSS tasarımların birleştirilmesi ve kontrol edilmesi 
Ortam: Electron.js, HTML, CSS
Beklenen Çıktı: Code Commitleri

**Comment by FeyzaBiber** [comment]
**Uyarı:** Bu taskın başlangıcı diğer taskların sonlanmasına bağlantılı olabilir!

- #73 
- #72 
- #71 
- #66 
- #69

**Comment by sinanaksu** [comment]
Completed
