### ISSUE TITLE
Tasarım: Icon Detay Componenti HTML/CSS Tasarımı

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/icon-wizard#69]
Türü: Geliştirme, Tasarım
Tanım: Figmadaki icon detay ekranı baz alınarak HTML ve CSS tasarımların oluşturulması
Ortam: HTML , CSS
Beklenen Çıktı: Farklı Branchde Code Commitleri

**Comment by Eralpozcan** [comment]
- Yapıldı.
