### ISSUE TITLE
Araştır: Firefox ve Opera'ya Setup Affilate Durumunu Sormak

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/icon-wizard#74]
Türü: Araştırma
Tanım: Firefox ve Opera'ya setup affilate durumunu sormak için mail atılması
Beklenen Çıktı: Gelen Mail Cevapları

**Comment by sinanaksu** [comment]
Firefox, Opera, CCleaner, Avast Antivirus şirketlerine 09.01.2022'de mail atıldı. Cevap bekleniyor.
